export const INITIAL_CATEGORIES = [
  {
    _id: 'cat-1',
    name: 'Drones',
    slug: 'drones',
    description: 'High-performance camera drones, mini drones, and professional aerial photography gear.',
    image: 'https://images.unsplash.com/photo-1507582020434-97210e740b79?w=800&auto=format&fit=crop&q=80',
    productCount: 2,
    displayOrder: 1,
    isActive: true
  },
  {
    _id: 'cat-2',
    name: 'Toys & Monster Trucks',
    slug: 'toys-monster-trucks',
    description: 'Rugged 4x4 monster trucks, die-cast vehicles, and exciting durable play sets for all ages.',
    image: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&auto=format&fit=crop&q=80',
    productCount: 2,
    displayOrder: 2,
    isActive: true
  },
  {
    _id: 'cat-3',
    name: 'Bulbs & Tubes',
    slug: 'bulbs-tubes',
    description: 'Energy-saving LED smart bulbs, ambient tube lights, and architectural lighting solutions.',
    image: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=800&auto=format&fit=crop&q=80',
    productCount: 2,
    displayOrder: 3,
    isActive: true
  },
  {
    _id: 'cat-4',
    name: 'Wires & Cables',
    slug: 'wires-cables',
    description: 'Heavy-duty electrical wires, shielded copper conduits, and domestic wiring essentials.',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    productCount: 2,
    displayOrder: 4,
    isActive: true
  },
  {
    _id: 'cat-5',
    name: 'Chargers',
    slug: 'chargers',
    description: 'Ultra-fast GaN power adapters, multi-device charging docks, and universal mobile chargers.',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
    productCount: 2,
    displayOrder: 5,
    isActive: true
  },
  {
    _id: 'cat-6',
    name: 'RC Toys',
    slug: 'rc-toys',
    description: 'Remote-controlled racing cars, acrobatic helicopters, drift vehicles, and speed boats.',
    image: 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=800&auto=format&fit=crop&q=80',
    productCount: 2,
    displayOrder: 6,
    isActive: true
  },
  {
    _id: 'cat-7',
    name: 'Mixers & Kitchen Appliances',
    slug: 'mixers-kitchen-appliances',
    description: 'High-speed blender mixers, multi-jar food processors, and heavy-duty kitchen appliances.',
    image: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800&auto=format&fit=crop&q=80',
    productCount: 2,
    displayOrder: 7,
    isActive: true
  },
  {
    _id: 'cat-8',
    name: 'Others',
    slug: 'others',
    description: 'Versatile electronic accessories, everyday utility essentials, and lifestyle tech gadgets.',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&auto=format&fit=crop&q=80',
    productCount: 2,
    displayOrder: 8,
    isActive: true
  }
];

export const INITIAL_PRODUCTS = [
  {
    _id: 'prod-1',
    name: 'SkyHawk 4K Ultra HD Drone',
    slug: 'skyhawk-4k-ultra-hd-drone',
    description: 'Foldable GPS camera drone with 3-axis gimbal, 35-min flight time, and auto-return feature.',
    detailedDescription: 'The SkyHawk 4K Ultra HD Drone delivers stunning cinematic aerial footage with its Sony CMOS sensor, 4K 60fps recording, and level-6 wind resistance. Equipped with smart obstacle avoidance sensors and 10km video transmission.',
    price: 49999,
    stock: 12,
    category: { _id: 'cat-1', name: 'Drones', slug: 'drones' },
    image: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1507582020434-97210e740b79?w=800&auto=format&fit=crop&q=80'
    ],
    ratingAvg: 4.8,
    ratingCount: 34,
    isAvailable: true,
    isActive: true
  },
  {
    _id: 'prod-2',
    name: 'Titan 4WD Rock Crawler Monster Truck',
    slug: 'titan-4wd-rock-crawler-monster-truck',
    description: 'Giant scale 1:12 off-road rock crawler with independent suspension and dual-motor torque.',
    detailedDescription: 'Conquer mud, gravel, and rough terrain with the Titan 4WD. Engineered with high-torque magnetic motors, metal shock absorbers, and anti-skid rubber oversized tires.',
    price: 3499,
    stock: 18,
    category: { _id: 'cat-2', name: 'Toys & Monster Trucks', slug: 'toys-monster-trucks' },
    image: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&auto=format&fit=crop&q=80'],
    ratingAvg: 4.7,
    ratingCount: 42,
    isAvailable: true,
    isActive: true
  },
  {
    _id: 'prod-3',
    name: 'Lumina Smart RGBW LED Bulb (12W)',
    slug: 'lumina-smart-rgbw-led-bulb-12w',
    description: '16 Million colors, voice control with Alexa/Google Home, and dimmable warmth settings.',
    detailedDescription: 'Transform any room with Lumina Smart RGBW. Connects directly via WiFi without a hub. Supports custom schedules and music syncing.',
    price: 899,
    stock: 80,
    category: { _id: 'cat-3', name: 'Bulbs & Tubes', slug: 'bulbs-tubes' },
    image: 'https://images.unsplash.com/photo-1550985543-f47f38aeee65?w=800&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1550985543-f47f38aeee65?w=800&auto=format&fit=crop&q=80'],
    ratingAvg: 4.6,
    ratingCount: 68,
    isAvailable: true,
    isActive: true
  },
  {
    _id: 'prod-4',
    name: 'VoltSafe 2.5 sq.mm FR Industrial Copper Wire (90m)',
    slug: 'voltsafe-2-5-sq-mm-fr-industrial-copper-wire-90m',
    description: 'Flame retardant 100% electrolytic pure copper wire spool for domestic and commercial wiring.',
    detailedDescription: 'IS-certified 2.5mm multi-strand copper cable with advanced flame-retardant PVC insulation.',
    price: 2699,
    stock: 30,
    category: { _id: 'cat-4', name: 'Wires & Cables', slug: 'wires-cables' },
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80'],
    ratingAvg: 4.9,
    ratingCount: 51,
    isAvailable: true,
    isActive: true
  },
  {
    _id: 'prod-5',
    name: 'PowerVolt 65W GaN Fast Charger',
    slug: 'powervolt-65w-gan-fast-charger',
    description: 'Compact 3-port GaN III wall charger supporting Type-C PD 3.0 and QC 4.0 for laptops and phones.',
    detailedDescription: 'Powered by Gallium Nitride (GaN) technology, this ultra-portable 65W brick charges laptops and phones simultaneously.',
    price: 2499,
    stock: 22,
    category: { _id: 'cat-5', name: 'Chargers', slug: 'chargers' },
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80'],
    ratingAvg: 4.8,
    ratingCount: 74,
    isAvailable: true,
    isActive: true
  },
  {
    _id: 'prod-6',
    name: 'SpeedDemon 1:16 High-Speed RC Drift Car',
    slug: 'speeddemon-1-16-high-speed-rc-drift-car',
    description: '2.4GHz 40km/h remote control drift car with spare drift tires, gyro assist, and LED headlights.',
    detailedDescription: 'Engineered for high-speed drifting thrills. Comes with an electronic stability control gyro.',
    price: 4599,
    stock: 11,
    category: { _id: 'cat-6', name: 'RC Toys', slug: 'rc-toys' },
    image: 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=800&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=800&auto=format&fit=crop&q=80'],
    ratingAvg: 4.7,
    ratingCount: 26,
    isAvailable: true,
    isActive: true
  },
  {
    _id: 'prod-7',
    name: 'MasterChef 1000W Heavy-Duty Mixer Grinder',
    slug: 'masterchef-1000w-heavy-duty-mixer-grinder',
    description: 'Copper motor mixer with 3 stainless steel jars, pulse control, and overload protector.',
    detailedDescription: 'Crush the toughest spices, batters, and purees effortlessly with the MasterChef 1000W.',
    price: 4999,
    stock: 16,
    category: { _id: 'cat-7', name: 'Mixers & Kitchen Appliances', slug: 'mixers-kitchen-appliances' },
    image: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800&auto=format&fit=crop&q=80'],
    ratingAvg: 4.9,
    ratingCount: 88,
    isAvailable: true,
    isActive: true
  },
  {
    _id: 'prod-8',
    name: 'OmniPlug Universal Travel Power Adapter',
    slug: 'omniplug-universal-travel-power-adapter',
    description: 'All-in-one worldwide international adapter with 4 USB ports and Type-C 30W output.',
    detailedDescription: 'Works in more than 150 countries including US, UK, EU, AU, and Asia.',
    price: 1499,
    stock: 35,
    category: { _id: 'cat-8', name: 'Others', slug: 'others' },
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&auto=format&fit=crop&q=80'],
    ratingAvg: 4.6,
    ratingCount: 52,
    isAvailable: true,
    isActive: true
  }
];
